---
- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    
- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes
    
- name: "Install dependencies [nodejs and npm]."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create Backend App Directory"
  file:
    path: ~/backend-app_dir
    state: directory
    
- name: "Copy artifact into Instance"
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app_dir/artifact.tar.gz
    
- name: "start app"
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 stop all
    pm2 start npm -- start
    
    
    
    
  

